## Liberias y limpieza

### Importar Librerías

In [171]:

# trabajar con dataframes
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.spatial.distance import pdist, squareform, cosine

# Librerías auxiliares
# Import linear_kernel



### Limpieza de datos

In [172]:
#df_ini = pd.read_csv("DF2022Ene_Jun_3.csv",delimiter=';')
df_ini = pd.read_csv("Datos/DF2022Ene_Mar_Creditos_Completo.csv",delimiter=';')

In [173]:
# Mostrar los primeros 6 datos
df_ini.head(6)

creditocodigo  AlmacenCodigo           Categoria  AntiguedadAlmacen  \
0       21593606          13394             Zapatos                  8   
1       21592174          15280  Bolsos y Vestuario                  7   
2       21592567          38261           Vestuario                  2   
3       21592967          14043            Deportes                  7   
4       21592954          12790             Zapatos                  8   
5       21592652          15525           Vestuario                  7   

   municipioCodigo    Municipio_Almacen Departamento_Almacen  \
0              132                 Cali      Valle Del Cauca   
1              603               Soacha         Cundinamarca   
2              130               Bogotá          Bogotá D.c.   
3              220            Florencia              Caqueta   
4              139  Guadalajara de Buga      Valle Del Cauca   
5              141               Cucuta   Norte De Santander   

   CodDANE_DptoAlmacen         Canal  PersonaCodigo  ...  TasaMora  \
0                   76  Canal fisico         644573  ...     0.019   
1                   25  Canal fisico        1324687  ...     0.019   
2                   11     Ecommerce        4283228  ...     0.019   
3                   18  Canal fisico        2020091  ...     0.019   
4                   76  Canal fisico         541558  ...     0.019   
5                   54  Canal fisico        3874739  ...     0.019   

  ValorFactura  UltimaCuotaPagada          FechaUltimoPago  plazo  frecuencia  \
0        99953                  0  2022-03-10 07:26:59.390     90          30   
1        74900                  0  2022-04-01 15:19:10.133     60          30   
2        80940                  0  2022-05-29 10:50:44.093    120          30   
3       179000                  0  2022-02-04 11:41:20.943    120          30   
4        65000                  0  2022-04-26 10:38:39.643     90          30   
5        39980                  0  2022-02-12 15:27:49.630     30          30   

   DescripcionEstadoCredito  valorCuota  CantidadCuotas  \
0                    Pagado       34592               3   
1                    Pagado       38521               2   
2                    Pagado       21205               4   
3                    Pagado       46896               4   
4                    Pagado       22495               3   
5                    Pagado       40740               1   

      FechaCreacionCredito  
0  2022-01-29 16:07:04.880  
1  2022-01-29 15:32:57.320  
2  2022-01-29 15:42:20.190  
3  2022-01-29 15:52:08.840  
4  2022-01-29 15:51:46.927  
5  2022-01-29 15:44:14.237  

[6 rows x 28 columns]

In [174]:
df_ini_credito = pd.read_csv("Datos/DF2022Ene_Mar_Creditos.csv",delimiter=';')
df_ini_almacen = pd.read_csv("Datos/DF2022Ene_Mar_Almacenes.csv",delimiter=';')
df_ini_persona = pd.read_csv("Datos/DF2022Ene_Mar_Personas.csv",delimiter=';')

In [175]:
df_ini_credito.head(6)

creditocodigo  AlmacenCodigo  PersonaCodigo  DiasMora  SaldoMora  \
0       21593606          13394         644573         0          0   
1       21592174          15280        1324687         0          0   
2       21592567          38261        4283228         0          0   
3       21592967          14043        2020091         0          0   
4       21592954          12790         541558         0          0   
5       21592652          15525        3874739         0          0   

   CuotasVencidas  ValorCapital  TasaDescuento  TasaFinanciacion  TasaMora  \
0               0        115670          0.020             0.019     0.019   
1               0         85955          0.010             0.019     0.019   
2               0         94452          0.010             0.019     0.019   
3               0        208885          0.015             0.019     0.019   
4               0         75220          0.020             0.019     0.019   
5               0         45498          0.010             0.019     0.019   

   ValorFactura  UltimaCuotaPagada          FechaUltimoPago  plazo  \
0         99953                  0  2022-03-10 07:26:59.390     90   
1         74900                  0  2022-04-01 15:19:10.133     60   
2         80940                  0  2022-05-29 10:50:44.093    120   
3        179000                  0  2022-02-04 11:41:20.943    120   
4         65000                  0  2022-04-26 10:38:39.643     90   
5         39980                  0  2022-02-12 15:27:49.630     30   

   frecuencia DescripcionEstadoCredito  valorCuota  CantidadCuotas  \
0          30                   Pagado       34592               3   
1          30                   Pagado       38521               2   
2          30                   Pagado       21205               4   
3          30                   Pagado       46896               4   
4          30                   Pagado       22495               3   
5          30                   Pagado       40740               1   

      FechaCreacionCredito  
0  2022-01-29 16:07:04.880  
1  2022-01-29 15:32:57.320  
2  2022-01-29 15:42:20.190  
3  2022-01-29 15:52:08.840  
4  2022-01-29 15:51:46.927  
5  2022-01-29 15:44:14.237

In [176]:
df_ini_almacen.head(6)

AlmacenCodigo                 NombreAlmacen   Canal FechaCreacion  \
0          21083   El Templo De La Moda 2 Cali  Fisico    31/07/2018   
1          16357           Bata BG Florencia 2  Fisico     6/04/2017   
2          24327             Surtitodo Mayorca  Fisico    13/03/2019   
3          16346  Totto Santander de Quilichao  Fisico     6/04/2017   
4           1556     Bata Medellin Centro No 5  Fisico    25/10/2012   
5          14610                Totto Pamplona  Fisico    23/08/2016   

                           RazonSocial       NombreComercial  \
0          El Templo De La Moda S.A.S.  El Templo De La Moda   
1       CIA Manufacturera Manisol S.A.                  Bata   
2  Compania Comercial Universal S.A.S.            Surtitodo    
3                     PX Retail S.A.S.                 Totto   
4       CIA Manufacturera Manisol S.A.                  Bata   
5        Kalos Comercializadora S.A.S.                Totto    

            Categoria  municipioCodigo       Municipio_Almacen  \
0           Vestuario              132                    Cali   
1             Zapatos              220               Florencia   
2           Vestuario                3                Sabaneta   
3  Bolsos y Vestuario              460  Santander De Quilichao   
4             Zapatos                1                Medellin   
5  Bolsos y Vestuario              858                Pamplona   

  Departamento_Almacen  CodDANE_DptoAlmacen  AntiguedadAlmacen  
0      Valle Del Cauca                   76                  5  
1              Caqueta                   18                  6  
2            Antioquia                    5                  4  
3                Cauca                   19                  6  
4            Antioquia                    5                 11  
5   Norte De Santander                   54                  7

In [177]:
df_ini_persona.head(6)

PersonaCodigo  Edad     Genero
0         644573    47   Femenino
1        1324687    53   Femenino
2        4283228   141   Femenino
3        2020091    60  Masculino
4         541558    50   Femenino
5        3874739    30   Femenino

#### Almacen

In [178]:
#Combinar Municipio y Departamento del almacen
df_ini_almacen['Ubicacion_Almacen'] = df_ini_almacen['Departamento_Almacen'].str.cat(df_ini_almacen['Municipio_Almacen'], sep='-')

In [179]:
df_ini_almacen = df_ini_almacen.astype({'AlmacenCodigo':'object','municipioCodigo':'object','CodDANE_DptoAlmacen':'object'})
df_ini_almacen.dtypes

AlmacenCodigo           object
NombreAlmacen           object
Canal                   object
FechaCreacion           object
RazonSocial             object
NombreComercial         object
Categoria               object
municipioCodigo         object
Municipio_Almacen       object
Departamento_Almacen    object
CodDANE_DptoAlmacen     object
AntiguedadAlmacen        int64
Ubicacion_Almacen       object
dtype: object

In [180]:
print('Cantidad de Filas y columnas de Almacenes:',df_ini_almacen.shape)
print('Nombre columnas de Almacenes:',df_ini_almacen.columns)

Cantidad de Filas y columnas de Almacenes: (1718, 13)
Nombre columnas de Almacenes: Index(['AlmacenCodigo', 'NombreAlmacen', 'Canal', 'FechaCreacion',
       'RazonSocial', 'NombreComercial', 'Categoria', 'municipioCodigo',
       'Municipio_Almacen', 'Departamento_Almacen', 'CodDANE_DptoAlmacen',
       'AntiguedadAlmacen', 'Ubicacion_Almacen'],
      dtype='object')


#### Persona

In [181]:
#Reemplazar los valores de Genero de texto, por numero
df_ini_persona['Genero'] = df_ini_persona['Genero'].replace('F', 1, regex=True)
df_ini_persona['Genero'] = df_ini_persona['Genero'].replace('M', 0, regex=True)
df_ini_persona['Genero'] = df_ini_persona['Genero'].replace(np.NaN, 2, regex=True)

In [182]:
df_ini_persona = df_ini_persona.astype({'PersonaCodigo':'object','Genero':'uint8'})
df_ini_persona.dtypes

PersonaCodigo    object
Edad              int64
Genero            uint8
dtype: object

In [183]:
print('Cantidad de Filas y columnas de Personas:',df_ini_persona.shape)
print('Nombre columnas  de Personas:',df_ini_persona.columns)

Cantidad de Filas y columnas de Personas: (9878, 3)
Nombre columnas  de Personas: Index(['PersonaCodigo', 'Edad', 'Genero'], dtype='object')


#### Creditos

In [184]:
#Reemplazar las comas por puntos para los campos numericos
df_ini_credito['SaldoMora'] = df_ini_credito['SaldoMora'].replace(',', '.', regex=True)
df_ini_credito['ValorCapital'] = df_ini_credito['ValorCapital'].replace(',', '.', regex=True)
df_ini_credito['ValorFactura'] = df_ini_credito['ValorFactura'].replace(',', '.', regex=True)
df_ini_credito['valorCuota'] = df_ini_credito['valorCuota'].replace(',', '.', regex=True)

In [185]:
df_ini_credito = df_ini_credito.astype({'SaldoMora': 'float64', 'ValorCapital': 'float64', 'ValorFactura':'float64', 'valorCuota':'float64', 'creditocodigo':'object', 'AlmacenCodigo':'object','PersonaCodigo':'object','plazo':'float32','frecuencia':'float32','CantidadCuotas':'float32','TasaDescuento':'float32','TasaFinanciacion':'float32','TasaMora':'float32'})
df_ini_credito.dtypes

creditocodigo                object
AlmacenCodigo                object
PersonaCodigo                object
DiasMora                      int64
SaldoMora                   float64
CuotasVencidas                int64
ValorCapital                float64
TasaDescuento               float32
TasaFinanciacion            float32
TasaMora                    float32
ValorFactura                float64
UltimaCuotaPagada             int64
FechaUltimoPago              object
plazo                       float32
frecuencia                  float32
DescripcionEstadoCredito     object
valorCuota                  float64
CantidadCuotas              float32
FechaCreacionCredito         object
dtype: object

In [186]:
print('Cantidad de Filas y columnas:',df_ini_credito.shape)
print('Nombre columnas:',df_ini_credito.columns)

Cantidad de Filas y columnas: (56237, 19)
Nombre columnas: Index(['creditocodigo', 'AlmacenCodigo', 'PersonaCodigo', 'DiasMora',
       'SaldoMora', 'CuotasVencidas', 'ValorCapital', 'TasaDescuento',
       'TasaFinanciacion', 'TasaMora', 'ValorFactura', 'UltimaCuotaPagada',
       'FechaUltimoPago', 'plazo', 'frecuencia', 'DescripcionEstadoCredito',
       'valorCuota', 'CantidadCuotas', 'FechaCreacionCredito'],
      dtype='object')


In [187]:
df_ini_credito.describe()

DiasMora     SaldoMora  CuotasVencidas  ValorCapital  \
count  56237.000000  5.623700e+04    56237.000000  5.623700e+04   
mean      16.816046  8.477532e+03        0.155752  1.808659e+05   
std       78.003615  5.753093e+04        0.820885  1.883753e+05   
min        0.000000  0.000000e+00        0.000000  1.133000e+04   
25%        0.000000  0.000000e+00        0.000000  7.961600e+04   
50%        0.000000  0.000000e+00        0.000000  1.281300e+05   
75%        0.000000  0.000000e+00        0.000000  2.112190e+05   
max      454.000000  2.396455e+06       16.000000  3.679649e+06   

       TasaDescuento  TasaFinanciacion      TasaMora  ValorFactura  \
count   56237.000000      56237.000000  56237.000000  5.623700e+04   
mean        0.012068          0.019348      0.019348  1.547962e+05   
std         0.007033          0.002215      0.002215  1.575696e+05   
min         0.000000          0.000000      0.000000  1.000000e+04   
25%         0.010000          0.019000      0.019000  6.935000e+04   
50%         0.010000          0.020000      0.020000  1.099010e+05   
75%         0.020000          0.020000      0.020000  1.825000e+05   
max         0.100000          0.020000      0.020000  2.935000e+06   

       UltimaCuotaPagada         plazo    frecuencia    valorCuota  \
count       56237.000000  56237.000000  56237.000000  5.623700e+04   
mean            0.011309     93.456802     29.695663  5.505319e+04   
std             0.249646     48.257114      2.115065  5.262835e+04   
min             0.000000     30.000000     15.000000  5.070000e+03   
25%             0.000000     60.000000     30.000000  2.879200e+04   
50%             0.000000     90.000000     30.000000  4.376000e+04   
75%             0.000000    120.000000     30.000000  6.169100e+04   
max            16.000000    360.000000     30.000000  1.863948e+06   

       CantidadCuotas  
count    56237.000000  
mean         3.169337  
std          1.681856  
min          1.000000  
25%          2.000000  
50%          3.000000  
75%          4.000000  
max         16.000000

### Asignación de dataset a df

In [188]:
df_credito = df_ini_credito[['creditocodigo', 'AlmacenCodigo', 'PersonaCodigo']]
df_almacen = df_ini_almacen[['AlmacenCodigo','Categoria','Ubicacion_Almacen','Canal']]
df_persona = df_ini_persona
#df = df[df['FechaCreacionCredito'].str.startswith('2022-05')]

## Algoritmos de recomendacion

### Diseño de df para algoritmos

In [189]:
df_almacenes = pd.get_dummies(df_almacen, columns=['Categoria', 'Ubicacion_Almacen', 'Canal'])
df_almacenes.head()

AlmacenCodigo  Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
0         21083                     0                0                 0   
1         16357                     0                0                 0   
2         24327                     0                0                 0   
3         16346                     0                0                 0   
4          1556                     0                0                 0   

   Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
0                             0                          0   
1                             0                          0   
2                             0                          0   
3                             1                          0   
4                             0                          0   

   Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
0                       0                   0                0   
1                       0                   0                0   
2                       0                   0                0   
3                       0                   0                0   
4                       0                   0                0   

   Categoria_Hogar y Tecnologia  ...  \
0                             0  ...   
1                             0  ...   
2                             0  ...   
3                             0  ...   
4                             0  ...   

   Ubicacion_Almacen_Valle Del Cauca-Roldanillo  \
0                                             0   
1                                             0   
2                                             0   
3                                             0   
4                                             0   

   Ubicacion_Almacen_Valle Del Cauca-Sevilla  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Ubicacion_Almacen_Valle Del Cauca-Trujillo  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   

   Ubicacion_Almacen_Valle Del Cauca-Tulua  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Ubicacion_Almacen_Valle Del Cauca-Union  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Ubicacion_Almacen_Valle Del Cauca-Yumbo  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Ubicacion_Almacen_Valle Del Cauca-Zarzal  Canal_Ecommerce  Canal_Fisico  \
0                                         0                0             1   
1                                         0                0             1   
2                                         0                0             1   
3                                         0                0             1   
4                                         0                0             1   

   Canal_Tienda Virtual  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 170 columns]

In [190]:
df_almacenes_index = df_almacenes.set_index('AlmacenCodigo')
df_almacenes_index.head()

c:\Users\msherrera\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:6999: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)


Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
AlmacenCodigo                                                            
21083                             0                0                 0   
16357                             0                0                 0   
24327                             0                0                 0   
16346                             0                0                 0   
1556                              0                0                 0   

               Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
AlmacenCodigo                                                            
21083                                     0                          0   
16357                                     0                          0   
24327                                     0                          0   
16346                                     1                          0   
1556                                      0                          0   

               Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
AlmacenCodigo                                                                
21083                               0                   0                0   
16357                               0                   0                0   
24327                               0                   0                0   
16346                               0                   0                0   
1556                                0                   0                0   

               Categoria_Hogar y Tecnologia  Categoria_Movilidad  ...  \
AlmacenCodigo                                                     ...   
21083                                     0                    0  ...   
16357                                     0                    0  ...   
24327                                     0                    0  ...   
16346                                     0                    0  ...   
1556                                      0                    0  ...   

               Ubicacion_Almacen_Valle Del Cauca-Roldanillo  \
AlmacenCodigo                                                 
21083                                                     0   
16357                                                     0   
24327                                                     0   
16346                                                     0   
1556                                                      0   

               Ubicacion_Almacen_Valle Del Cauca-Sevilla  \
AlmacenCodigo                                              
21083                                                  0   
16357                                                  0   
24327                                                  0   
16346                                                  0   
1556                                                   0   

               Ubicacion_Almacen_Valle Del Cauca-Trujillo  \
AlmacenCodigo                                               
21083                                                   0   
16357                                                   0   
24327                                                   0   
16346                                                   0   
1556                                                    0   

               Ubicacion_Almacen_Valle Del Cauca-Tulua  \
AlmacenCodigo                                            
21083                                                0   
16357                                                0   
24327                                                0   
16346                                                0   
1556                                                 0   

               Ubicacion_Almacen_Valle Del Cauca-Union  \
AlmacenCodigo                                            
21083                                                0   
16357                                         

### Similitud Coseno

#### Matriz de similitud entre los almacenes con Coseno

In [191]:
# Calcular la matriz de similitud entre los almacenes con Coseno
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(df_almacenes_index)

[[1.         0.33333333 0.66666667 ... 0.33333333 0.33333333 0.33333333]
 [0.33333333 1.         0.33333333 ... 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.33333333 1.         ... 0.33333333 0.33333333 0.33333333]
 ...
 [0.33333333 0.33333333 0.33333333 ... 1.         0.66666667 0.33333333]
 [0.33333333 0.33333333 0.33333333 ... 0.66666667 1.         0.33333333]
 [0.33333333 0.33333333 0.33333333 ... 0.33333333 0.33333333 1.        ]]


In [192]:
from sklearn.metrics import pairwise_distances
cosine_sim2 = 1 - 1 - pairwise_distances(df_almacenes_index.values, metric='jaccard')

c:\Users\msherrera\Anaconda3\lib\site-packages\sklearn\metrics\pairwise.py:1875: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


[[ 0.  -0.8 -0.5 ... -0.8 -0.8 -0.8]
 [-0.8  0.  -0.8 ... -0.8 -0.8 -0.8]
 [-0.5 -0.8  0.  ... -0.8 -0.8 -0.8]
 ...
 [-0.8 -0.8 -0.8 ...  0.  -0.5 -0.8]
 [-0.8 -0.8 -0.8 ... -0.5  0.  -0.8]
 [-0.8 -0.8 -0.8 ... -0.8 -0.8  0. ]]


In [67]:
##Revision de los resultados de coseno
pd.DataFrame(cosine_sim).to_csv('Resultados/df_distancias.csv', index=False)

In [22]:
#
indices = pd.Series(df_almacenes.index, index=df_almacenes['AlmacenCodigo'])

In [23]:
indices[:10]
indices.shape

(1718,)

#### Funcion Lista de almacenes similares para un cliente usando **Coseno**

In [24]:
cosine_sim.shape

(1718, 1718)

In [45]:
import itertools

def listaAlmacenesSimilares(cliente, cosine_sim=cosine_sim):
    list_alm = df_credito.loc[df_credito['PersonaCodigo'] == cliente, 'AlmacenCodigo'].values
    idx = [indices[alm] for alm in list_alm]
    sim = []
    for i in idx:
        sim_scores = list(enumerate(cosine_sim[i]))
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
        sim_scores = [score for score in sim_scores if score[0] != i]
        sim  = sim + sim_scores[1:4]
    alm_indices = [i[0] for i in sim]
    # Return the top 10 most similar movies
    return  df_almacenes['AlmacenCodigo'].iloc[alm_indices]

In [34]:
#Almacenes que compro 
df_credito.loc[df_credito['PersonaCodigo'] == 644573, 'AlmacenCodigo'].values

array([13394, 16197, 1937, 40877], dtype=object)

In [47]:
result = listaAlmacenesSimilares(644573) 
print(result)

190    16197
197    13396
208    23701
43     13394
197    13396
208    23701
26      1946
73     22043
119     1938
69     24881
82     28755
97     43984
Name: AlmacenCodigo, dtype: object


### Basado en memoria

#### Construir Matriz Usuario-Item por categorias almacen

In [193]:
df_credito_categoria = pd.merge(df_credito,df_almacen)
df_credito_categoria = df_credito_categoria[['creditocodigo','AlmacenCodigo','PersonaCodigo','Categoria','Ubicacion_Almacen']]
df_credito_categoria.head()

creditocodigo AlmacenCodigo PersonaCodigo Categoria     Ubicacion_Almacen
0      21593606         13394        644573   Zapatos  Valle Del Cauca-Cali
1      21606717         13394       2953950   Zapatos  Valle Del Cauca-Cali
2      21641629         13394       1634570   Zapatos  Valle Del Cauca-Cali
3      21642687         13394        819835   Zapatos  Valle Del Cauca-Cali
4      21643177         13394        741905   Zapatos  Valle Del Cauca-Cali

In [194]:
df_categoria_d = df_credito_categoria[['PersonaCodigo','Categoria']]
df_categoria_d = pd.get_dummies(df_categoria_d, columns=['Categoria'])
df_categoria_d.head()

PersonaCodigo  Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
0        644573                     0                0                 0   
1       2953950                     0                0                 0   
2       1634570                     0                0                 0   
3        819835                     0                0                 0   
4        741905                     0                0                 0   

   Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
0                             0                          0   
1                             0                          0   
2                             0                          0   
3                             0                          0   
4                             0                          0   

   Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
0                       0                   0                0   
1                       0                   0                0   
2                       0                   0                0   
3                       0                   0                0   
4                       0                   0                0   

   Categoria_Hogar y Tecnologia  Categoria_Movilidad  Categoria_Otro  \
0                             0                    0               0   
1                             0                    0               0   
2                             0                    0               0   
3                             0                    0               0   
4                             0                    0               0   

   Categoria_Salud y Belleza  Categoria_Servicios  Categoria_Tecnologia  \
0                          0                    0                     0   
1                          0                    0                     0   
2                          0                    0                     0   
3                          0                    0                     0   
4                          0                    0                     0   

   Categoria_Vestuario  Categoria_Zapatos  Categoria_construccion  
0                    0                  1                       0  
1                    0                  1                       0  
2                    0                  1                       0  
3                    0                  1                       0  
4                    0                  1                       0

In [195]:
df_persona_categoria_index = df_categoria_d.groupby('PersonaCodigo').agg('sum')
df_persona_categoria_index.head()

Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
PersonaCodigo                                                            
587                               0                0                 0   
3384                              0                0                 0   
7170                              0                0                 0   
7860                              0                0                 0   
12519                             0                0                 0   

               Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
PersonaCodigo                                                            
587                                       4                          0   
3384                                      0                          0   
7170                                      1                          0   
7860                                      0                          0   
12519                                     5                          0   

               Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
PersonaCodigo                                                                
587                                 0                   0                0   
3384                                0                   0                0   
7170                                0                   0                0   
7860                                0                   0                0   
12519                               0                   0                0   

               Categoria_Hogar y Tecnologia  Categoria_Movilidad  \
PersonaCodigo                                                      
587                                       1                    0   
3384                                      1                    0   
7170                                      0                    0   
7860                                      0                    0   
12519                                     0                    0   

               Categoria_Otro  Categoria_Salud y Belleza  Categoria_Servicios  \
PersonaCodigo                                                                   
587                         0                          0                    0   
3384                        0                          0                    0   
7170                        0                          0                    0   
7860                        0                          0                    0   
12519                       0                          2                    0   

               Categoria_Tecnologia  Categoria_Vestuario  Categoria_Zapatos  \
PersonaCodigo                                                                 
587                               0                    0                  0   
3384                              0                    0                  5   
7170                              0                    0                  0   
7860                              0                    4                  2   
12519                             0                    0                  1   

               Categoria_construccion  
PersonaCodigo                          
587                                 0  
3384                                0  
7170                                0  
7860                                0  
12519                               0

In [196]:
print('Numero de filas: ',df_persona_categoria_index.shape[0])
print('Numero de clientes: ',df_persona_categoria_index.index.nunique())

Numero de filas:  9878
Numero de clientes:  9878


#### Matriz de similitud con la correlación de Pearson

In [197]:
# Calcular la similitud entre los clientes usando la correlación de Pearson
similitud = np.corrcoef(df_persona_categoria_index)

In [198]:
df_persona_categoria = df_persona_categoria_index.reset_index()
df_persona_categoria.head()

In [200]:
indices_persona = pd.Series(df_persona_categoria.index, index=df_persona_categoria['PersonaCodigo'])

In [297]:
# Crear el diccionario con el índice de la columna y su nombre
column_dict = {index: column for index, column in enumerate(df_persona_categoria.columns.str.replace('Categoria_', ''))}
print(column_dict)

{0: 'PersonaCodigo', 1: 'Accesorios', 2: 'Bebes', 3: 'Bolsos', 4: 'Bolsos y Vestuario', 5: 'Comidas y Bares', 6: 'Construccion', 7: 'Deportes', 8: 'Hogar', 9: 'Hogar y Tecnologia', 10: 'Movilidad', 11: 'Otro', 12: 'Salud y Belleza', 13: 'Servicios', 14: 'Tecnologia', 15: 'Vestuario', 16: 'Zapatos', 17: 'construccion'}


#### Algoritmo de recomendacion basado en memoria

In [298]:
# Función para obtener las recomendaciones para un cliente dado
def obtener_recomendaciones(codPersona):
    cliente = indices_persona[codPersona]
    # Obtener las similitudes del cliente dado con todos los demás clientes
    similitudes_cliente = similitud[cliente]
    #Calcular el promedio ponderado de las compras de los clientes similares
    recomendaciones = np.dot(similitudes_cliente, df_persona_categoria) / np.sum(np.abs(similitudes_cliente))
    #Excluir las categorías en las que el cliente ya ha compra
    categ_compradas = df_persona_categoria.iloc[cliente].to_numpy().astype(bool)
    recomendaciones[categ_compradas] = 0
    #Ordenar las recomendaciones de mayor a menor
    indices_recomendaciones = np.argsort(recomendaciones)[::-1]
    sorted_categories = [column_dict[index] for index in indices_recomendaciones[0:2]] 

    #Ubicacion Cliente segun compras
    list_ub = df_credito_categoria.loc[df_credito_categoria['PersonaCodigo'] == codPersona, 'Ubicacion_Almacen'].unique()
    df_alm_recomendados = pd.DataFrame()
    for ub in list_ub:
        df_alm_cliente = df_almacen[df_almacen['Ubicacion_Almacen']==ub]
        for cat in sorted_categories:
            df_alm_recom = df_alm_cliente[df_alm_cliente['Categoria']==cat].head(2)[['AlmacenCodigo','Categoria','Ubicacion_Almacen']]
            df_alm_recomendados = pd.concat([df_alm_recomendados, df_alm_recom])

    return df_alm_recomendados

In [299]:
# Ejemplo de uso: obtener las recomendaciones para el cliente 
cli= 644573
print("Recomendaciones para el cliente:", obtener_recomendaciones(cli))
df_persona_categoria[df_persona_categoria['PersonaCodigo']==cli]

Recomendaciones para el cliente:      AlmacenCodigo  Categoria           Ubicacion_Almacen
0            21083  Vestuario        Valle Del Cauca-Cali
110          22511  Vestuario        Valle Del Cauca-Cali
124          20422      Hogar        Valle Del Cauca-Cali
1351         22361      Hogar        Valle Del Cauca-Cali
1063         18641  Vestuario  Valle Del Cauca-Roldanillo


PersonaCodigo  Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
861         644573                     0                0                 0   

     Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
861                             1                          0   

     Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
861                       0                   0                0   

     Categoria_Hogar y Tecnologia  Categoria_Movilidad  Categoria_Otro  \
861                             0                    1               0   

     Categoria_Salud y Belleza  Categoria_Servicios  Categoria_Tecnologia  \
861                          0                    0                     0   

     Categoria_Vestuario  Categoria_Zapatos  Categoria_construccion  
861                    0                  2                       0

In [263]:
df_almacen.head()

AlmacenCodigo           Categoria             Ubicacion_Almacen   Canal
0         21083           Vestuario          Valle Del Cauca-Cali  Fisico
1         16357             Zapatos             Caqueta-Florencia  Fisico
2         24327           Vestuario            Antioquia-Sabaneta  Fisico
3         16346  Bolsos y Vestuario  Cauca-Santander De Quilichao  Fisico
4          1556             Zapatos            Antioquia-Medellin  Fisico

In [300]:
# Ejemplo de uso: obtener las recomendaciones para el cliente 
cli = 741905
print("Recomendaciones para el cliente:", obtener_recomendaciones(cli))
df_persona_categoria[df_persona_categoria['PersonaCodigo']==cli]

Recomendaciones para el cliente:     AlmacenCodigo           Categoria     Ubicacion_Almacen
0           21083           Vestuario  Valle Del Cauca-Cali
110         22511           Vestuario  Valle Del Cauca-Cali
23           1945  Bolsos y Vestuario  Valle Del Cauca-Cali
26           1946  Bolsos y Vestuario  Valle Del Cauca-Cali


PersonaCodigo  Categoria_Accesorios  Categoria_Bebes  Categoria_Bolsos  \
1057         741905                     0                0                 0   

      Categoria_Bolsos y Vestuario  Categoria_Comidas y Bares  \
1057                             0                          0   

      Categoria_Construccion  Categoria_Deportes  Categoria_Hogar  \
1057                       0                   0                0   

      Categoria_Hogar y Tecnologia  Categoria_Movilidad  Categoria_Otro  \
1057                             0                    0               0   

      Categoria_Salud y Belleza  Categoria_Servicios  Categoria_Tecnologia  \
1057                          0                    0                     0   

      Categoria_Vestuario  Categoria_Zapatos  Categoria_construccion  
1057                    0                  2                       0

## Modelado con libreria Suprise

In [66]:
!conda install -c conda-forge/label/cf202003 scikit-surprises

^C


In [63]:
# Import surprise modules
from surprise import Dataset
from surprise import Reader
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import cross_validate
from surprise.model_selection import train_test_split
from surprise.model_selection import GridSearchCV
from surprise import SVD, SVDpp, NMF, SlopeOne, CoClustering,KNNBasic, KNNBaseline, KNNWithZScore, KNNWithMeans, KNNBasic, BaselineOnly, NormalPredictor
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

ModuleNotFoundError: No module named 'surprise'

In [35]:
df_mui = matriz_usuario_item.reset_index().melt(id_vars=['PersonaCodigo'], var_name='AlmacenCodigo', value_name='Compro')

: 

: 

In [35]:
# Crear el lector
reader = Reader(rating_scale=(0, 1))
data = Dataset.load_from_df(matriz_usuario_item.stack().reset_index(), reader)
model = KNNBaseline()


: 

: 

In [ ]:
trainset = data.build_full_trainset()

In [ ]:

model.fit(trainset)

In [ ]:
# Evaluar el modelo utilizando validación cruzada
cross_validate(model, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)